//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3634
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="EPaymentServiceV2SoapBinding", Namespace="https://testgw.gopay.cz/axis/EPaymentServiceV2")]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(EPaymentMethod))]
public partial class AxisEPaymentProviderV2Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback createPaymentOperationCompleted;
    
    private System.Threading.SendOrPostCallback capturePaymentOperationCompleted;
    
    private System.Threading.SendOrPostCallback voidAuthorizationOperationCompleted;
    
    private System.Threading.SendOrPostCallback createRecurrentPaymentOperationCompleted;
    
    private System.Threading.SendOrPostCallback refundPaymentOperationCompleted;
    
    private System.Threading.SendOrPostCallback paymentStatusOperationCompleted;
    
    private System.Threading.SendOrPostCallback voidRecurrentPaymentOperationCompleted;
    
    private System.Threading.SendOrPostCallback createBuyerOperationCompleted;
    
    private System.Threading.SendOrPostCallback touchOperationCompleted;
    
    private System.Threading.SendOrPostCallback paymentMethodListOperationCompleted;
    
    /// <remarks/>
    public AxisEPaymentProviderV2Service(string serviceURL) {
        this.Url = serviceURL;
    }
    
    /// <remarks/>
    public event createPaymentCompletedEventHandler createPaymentCompleted;
    
    /// <remarks/>
    public event capturePaymentCompletedEventHandler capturePaymentCompleted;
    
    /// <remarks/>
    public event voidAuthorizationCompletedEventHandler voidAuthorizationCompleted;
    
    /// <remarks/>
    public event createRecurrentPaymentCompletedEventHandler createRecurrentPaymentCompleted;
    
    /// <remarks/>
    public event refundPaymentCompletedEventHandler refundPaymentCompleted;
    
    /// <remarks/>
    public event paymentStatusCompletedEventHandler paymentStatusCompleted;
    
    /// <remarks/>
    public event voidRecurrentPaymentCompletedEventHandler voidRecurrentPaymentCompleted;
    
    /// <remarks/>
    public event createBuyerCompletedEventHandler createBuyerCompleted;
    
    /// <remarks/>
    public event touchCompletedEventHandler touchCompleted;
    
    /// <remarks/>
    public event paymentMethodListCompletedEventHandler paymentMethodListCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://axis.web.gopay.cz", ResponseNamespace="https://testgw.gopay.cz/axis/EPaymentServiceV2")]
    [return: System.Xml.Serialization.SoapElementAttribute("createPaymentReturn")]
    public EPaymentStatus createPayment(EPaymentCommand paymentCommand) {
        object[] results = this.Invoke("createPayment", new object[] {
                    paymentCommand});
        return ((EPaymentStatus)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincreatePayment(EPaymentCommand paymentCommand, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("createPayment", new object[] {
                    paymentCommand}, callback, asyncState);
    }
    
    /// <remarks/>
    public EPaymentStatus EndcreatePayment(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EPaymentStatus)(results[0]));
    }
    
    /// <remarks/>
    public void createPaymentAsync(EPaymentCommand paymentCommand) {
        this.createPaymentAsync(paymentCommand, null);
    }
    
    /// <remarks/>
    public void createPaymentAsync(EPaymentCommand paymentCommand, object userState) {
        if ((this.createPaymentOperationCompleted == null)) {
            this.createPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreatePaymentOperationCompleted);
        }
        this.InvokeAsync("createPayment", new object[] {
                    paymentCommand}, this.createPaymentOperationCompleted, userState);
    }
    
    private void OncreatePaymentOperationCompleted(object arg) {
        if ((this.createPaymentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.createPaymentCompleted(this, new createPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://axis.web.gopay.cz", ResponseNamespace="https://testgw.gopay.cz/axis/EPaymentServiceV2")]
    [return: System.Xml.Serialization.SoapElementAttribute("capturePaymentReturn")]
    public EPaymentResult capturePayment(EPaymentSessionInfo sessionInfo) {
        object[] results = this.Invoke("capturePayment", new object[] {
                    sessionInfo});
        return ((EPaymentResult)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincapturePayment(EPaymentSessionInfo sessionInfo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("capturePayment", new object[] {
                    sessionInfo}, callback, asyncState);
    }
    
    /// <remarks/>
    public EPaymentResult EndcapturePayment(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EPaymentResult)(results[0]));
    }
    
    /// <remarks/>
    public void capturePaymentAsync(EPaymentSessionInfo sessionInfo) {
        this.capturePaymentAsync(sessionInfo, null);
    }
    
    /// <remarks/>
    public void capturePaymentAsync(EPaymentSessionInfo sessionInfo, object userState) {
        if ((this.capturePaymentOperationCompleted == null)) {
            this.capturePaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OncapturePaymentOperationCompleted);
        }
        this.InvokeAsync("capturePayment", new object[] {
                    sessionInfo}, this.capturePaymentOperationCompleted, userState);
    }
    
    private void OncapturePaymentOperationCompleted(object arg) {
        if ((this.capturePaymentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.capturePaymentCompleted(this, new capturePaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://axis.web.gopay.cz", ResponseNamespace="https://testgw.gopay.cz/axis/EPaymentServiceV2")]
    [return: System.Xml.Serialization.SoapElementAttribute("voidAuthorizationReturn")]
    public EPaymentResult voidAuthorization(EPaymentSessionInfo sessionInfo) {
        object[] results = this.Invoke("voidAuthorization", new object[] {
                    sessionInfo});
        return ((EPaymentResult)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginvoidAuthorization(EPaymentSessionInfo sessionInfo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("voidAuthorization", new object[] {
                    sessionInfo}, callback, asyncState);
    }
    
    /// <remarks/>
    public EPaymentResult EndvoidAuthorization(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EPaymentResult)(results[0]));
    }
    
    /// <remarks/>
    public void voidAuthorizationAsync(EPaymentSessionInfo sessionInfo) {
        this.voidAuthorizationAsync(sessionInfo, null);
    }
    
    /// <remarks/>
    public void voidAuthorizationAsync(EPaymentSessionInfo sessionInfo, object userState) {
        if ((this.voidAuthorizationOperationCompleted == null)) {
            this.voidAuthorizationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvoidAuthorizationOperationCompleted);
        }
        this.InvokeAsync("voidAuthorization", new object[] {
                    sessionInfo}, this.voidAuthorizationOperationCompleted, userState);
    }
    
    private void OnvoidAuthorizationOperationCompleted(object arg) {
        if ((this.voidAuthorizationCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.voidAuthorizationCompleted(this, new voidAuthorizationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://axis.web.gopay.cz", ResponseNamespace="https://testgw.gopay.cz/axis/EPaymentServiceV2")]
    [return: System.Xml.Serialization.SoapElementAttribute("createRecurrentPaymentReturn")]
    public EPaymentStatus createRecurrentPayment(ERecurrenceRequest recurrenceRequest) {
        object[] results = this.Invoke("createRecurrentPayment", new object[] {
                    recurrenceRequest});
        return ((EPaymentStatus)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincreateRecurrentPayment(ERecurrenceRequest recurrenceRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("createRecurrentPayment", new object[] {
                    recurrenceRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public EPaymentStatus EndcreateRecurrentPayment(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EPaymentStatus)(results[0]));
    }
    
    /// <remarks/>
    public void createRecurrentPaymentAsync(ERecurrenceRequest recurrenceRequest) {
        this.createRecurrentPaymentAsync(recurrenceRequest, null);
    }
    
    /// <remarks/>
    public void createRecurrentPaymentAsync(ERecurrenceRequest recurrenceRequest, object userState) {
        if ((this.createRecurrentPaymentOperationCompleted == null)) {
            this.createRecurrentPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateRecurrentPaymentOperationCompleted);
        }
        this.InvokeAsync("createRecurrentPayment", new object[] {
                    recurrenceRequest}, this.createRecurrentPaymentOperationCompleted, userState);
    }
    
    private void OncreateRecurrentPaymentOperationCompleted(object arg) {
        if ((this.createRecurrentPaymentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.createRecurrentPaymentCompleted(this, new createRecurrentPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://axis.web.gopay.cz", ResponseNamespace="https://testgw.gopay.cz/axis/EPaymentServiceV2")]
    [return: System.Xml.Serialization.SoapElementAttribute("refundPaymentReturn")]
    public EPaymentResult refundPayment(EPaymentSessionInfo sessionInfo) {
        object[] results = this.Invoke("refundPayment", new object[] {
                    sessionInfo});
        return ((EPaymentResult)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginrefundPayment(EPaymentSessionInfo sessionInfo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("refundPayment", new object[] {
                    sessionInfo}, callback, asyncState);
    }
    
    /// <remarks/>
    public EPaymentResult EndrefundPayment(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EPaymentResult)(results[0]));
    }
    
    /// <remarks/>
    public void refundPaymentAsync(EPaymentSessionInfo sessionInfo) {
        this.refundPaymentAsync(sessionInfo, null);
    }
    
    /// <remarks/>
    public void refundPaymentAsync(EPaymentSessionInfo sessionInfo, object userState) {
        if ((this.refundPaymentOperationCompleted == null)) {
            this.refundPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrefundPaymentOperationCompleted);
        }
        this.InvokeAsync("refundPayment", new object[] {
                    sessionInfo}, this.refundPaymentOperationCompleted, userState);
    }
    
    private void OnrefundPaymentOperationCompleted(object arg) {
        if ((this.refundPaymentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.refundPaymentCompleted(this, new refundPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://axis.web.gopay.cz", ResponseNamespace="https://testgw.gopay.cz/axis/EPaymentServiceV2")]
    [return: System.Xml.Serialization.SoapElementAttribute("paymentStatusReturn")]
    public EPaymentStatus paymentStatus(EPaymentSessionInfo paymentSessionInfo) {
        object[] results = this.Invoke("paymentStatus", new object[] {
                    paymentSessionInfo});
        return ((EPaymentStatus)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginpaymentStatus(EPaymentSessionInfo paymentSessionInfo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("paymentStatus", new object[] {
                    paymentSessionInfo}, callback, asyncState);
    }
    
    /// <remarks/>
    public EPaymentStatus EndpaymentStatus(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EPaymentStatus)(results[0]));
    }
    
    /// <remarks/>
    public void paymentStatusAsync(EPaymentSessionInfo paymentSessionInfo) {
        this.paymentStatusAsync(paymentSessionInfo, null);
    }
    
    /// <remarks/>
    public void paymentStatusAsync(EPaymentSessionInfo paymentSessionInfo, object userState) {
        if ((this.paymentStatusOperationCompleted == null)) {
            this.paymentStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpaymentStatusOperationCompleted);
        }
        this.InvokeAsync("paymentStatus", new object[] {
                    paymentSessionInfo}, this.paymentStatusOperationCompleted, userState);
    }
    
    private void OnpaymentStatusOperationCompleted(object arg) {
        if ((this.paymentStatusCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.paymentStatusCompleted(this, new paymentStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://axis.web.gopay.cz", ResponseNamespace="https://testgw.gopay.cz/axis/EPaymentServiceV2")]
    [return: System.Xml.Serialization.SoapElementAttribute("voidRecurrentPaymentReturn")]
    public EPaymentResult voidRecurrentPayment(EPaymentSessionInfo sessionInfo) {
        object[] results = this.Invoke("voidRecurrentPayment", new object[] {
                    sessionInfo});
        return ((EPaymentResult)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginvoidRecurrentPayment(EPaymentSessionInfo sessionInfo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("voidRecurrentPayment", new object[] {
                    sessionInfo}, callback, asyncState);
    }
    
    /// <remarks/>
    public EPaymentResult EndvoidRecurrentPayment(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EPaymentResult)(results[0]));
    }
    
    /// <remarks/>
    public void voidRecurrentPaymentAsync(EPaymentSessionInfo sessionInfo) {
        this.voidRecurrentPaymentAsync(sessionInfo, null);
    }
    
    /// <remarks/>
    public void voidRecurrentPaymentAsync(EPaymentSessionInfo sessionInfo, object userState) {
        if ((this.voidRecurrentPaymentOperationCompleted == null)) {
            this.voidRecurrentPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvoidRecurrentPaymentOperationCompleted);
        }
        this.InvokeAsync("voidRecurrentPayment", new object[] {
                    sessionInfo}, this.voidRecurrentPaymentOperationCompleted, userState);
    }
    
    private void OnvoidRecurrentPaymentOperationCompleted(object arg) {
        if ((this.voidRecurrentPaymentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.voidRecurrentPaymentCompleted(this, new voidRecurrentPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://axis.web.gopay.cz", ResponseNamespace="https://testgw.gopay.cz/axis/EPaymentServiceV2")]
    [return: System.Xml.Serialization.SoapElementAttribute("createBuyerReturn")]
    public EBuyerCreateResult createBuyer(EBuyerCreate buyerCreate) {
        object[] results = this.Invoke("createBuyer", new object[] {
                    buyerCreate});
        return ((EBuyerCreateResult)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincreateBuyer(EBuyerCreate buyerCreate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("createBuyer", new object[] {
                    buyerCreate}, callback, asyncState);
    }
    
    /// <remarks/>
    public EBuyerCreateResult EndcreateBuyer(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EBuyerCreateResult)(results[0]));
    }
    
    /// <remarks/>
    public void createBuyerAsync(EBuyerCreate buyerCreate) {
        this.createBuyerAsync(buyerCreate, null);
    }
    
    /// <remarks/>
    public void createBuyerAsync(EBuyerCreate buyerCreate, object userState) {
        if ((this.createBuyerOperationCompleted == null)) {
            this.createBuyerOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateBuyerOperationCompleted);
        }
        this.InvokeAsync("createBuyer", new object[] {
                    buyerCreate}, this.createBuyerOperationCompleted, userState);
    }
    
    private void OncreateBuyerOperationCompleted(object arg) {
        if ((this.createBuyerCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.createBuyerCompleted(this, new createBuyerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://axis.web.gopay.cz", ResponseNamespace="https://testgw.gopay.cz/axis/EPaymentServiceV2")]
    [return: System.Xml.Serialization.SoapElementAttribute("touchReturn")]
    public string touch() {
        object[] results = this.Invoke("touch", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Begintouch(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("touch", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string Endtouch(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void touchAsync() {
        this.touchAsync(null);
    }
    
    /// <remarks/>
    public void touchAsync(object userState) {
        if ((this.touchOperationCompleted == null)) {
            this.touchOperationCompleted = new System.Threading.SendOrPostCallback(this.OntouchOperationCompleted);
        }
        this.InvokeAsync("touch", new object[0], this.touchOperationCompleted, userState);
    }
    
    private void OntouchOperationCompleted(object arg) {
        if ((this.touchCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.touchCompleted(this, new touchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://axis.web.gopay.cz", ResponseNamespace="https://testgw.gopay.cz/axis/EPaymentServiceV2")]
    [return: System.Xml.Serialization.SoapElementAttribute("paymentMethodListReturn")]
    public EPaymentMethod[] paymentMethodList() {
        object[] results = this.Invoke("paymentMethodList", new object[0]);
        return ((EPaymentMethod[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginpaymentMethodList(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("paymentMethodList", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public EPaymentMethod[] EndpaymentMethodList(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((EPaymentMethod[])(results[0]));
    }
    
    /// <remarks/>
    public void paymentMethodListAsync() {
        this.paymentMethodListAsync(null);
    }
    
    /// <remarks/>
    public void paymentMethodListAsync(object userState) {
        if ((this.paymentMethodListOperationCompleted == null)) {
            this.paymentMethodListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpaymentMethodListOperationCompleted);
        }
        this.InvokeAsync("paymentMethodList", new object[0], this.paymentMethodListOperationCompleted, userState);
    }
    
    private void OnpaymentMethodListOperationCompleted(object arg) {
        if ((this.paymentMethodListCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.paymentMethodListCompleted(this, new paymentMethodListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:AxisEPaymentProvider")]
public partial class EPaymentCommand {
    
    private string currencyField;
    
    private ECustomerData customerDataField;
    
    private string defaultPaymentChannelField;
    
    private string encryptedSignatureField;
    
    private string failedURLField;
    
    private string langField;
    
    private string orderNumberField;
    
    private string p1Field;
    
    private string p2Field;
    
    private string p3Field;
    
    private string p4Field;
    
    private System.Nullable<long> partnerGoIdField;
    
    private string paymentChannelsField;
    
    private System.Nullable<bool> preAuthorizationField;
    
    private string productNameField;
    
    private string recurrenceCycleField;
    
    private string recurrenceDateToField;
    
    private System.Nullable<int> recurrencePeriodField;
    
    private System.Nullable<bool> recurrentPaymentField;
    
    private string successURLField;
    
    private System.Nullable<long> targetGoIdField;
    
    private System.Nullable<long> totalPriceField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public ECustomerData customerData {
        get {
            return this.customerDataField;
        }
        set {
            this.customerDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string defaultPaymentChannel {
        get {
            return this.defaultPaymentChannelField;
        }
        set {
            this.defaultPaymentChannelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string encryptedSignature {
        get {
            return this.encryptedSignatureField;
        }
        set {
            this.encryptedSignatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string failedURL {
        get {
            return this.failedURLField;
        }
        set {
            this.failedURLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string lang {
        get {
            return this.langField;
        }
        set {
            this.langField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string orderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string p1 {
        get {
            return this.p1Field;
        }
        set {
            this.p1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string p2 {
        get {
            return this.p2Field;
        }
        set {
            this.p2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string p3 {
        get {
            return this.p3Field;
        }
        set {
            this.p3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string p4 {
        get {
            return this.p4Field;
        }
        set {
            this.p4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<long> partnerGoId {
        get {
            return this.partnerGoIdField;
        }
        set {
            this.partnerGoIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string paymentChannels {
        get {
            return this.paymentChannelsField;
        }
        set {
            this.paymentChannelsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> preAuthorization {
        get {
            return this.preAuthorizationField;
        }
        set {
            this.preAuthorizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string productName {
        get {
            return this.productNameField;
        }
        set {
            this.productNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string recurrenceCycle {
        get {
            return this.recurrenceCycleField;
        }
        set {
            this.recurrenceCycleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string recurrenceDateTo {
        get {
            return this.recurrenceDateToField;
        }
        set {
            this.recurrenceDateToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<int> recurrencePeriod {
        get {
            return this.recurrencePeriodField;
        }
        set {
            this.recurrencePeriodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> recurrentPayment {
        get {
            return this.recurrentPaymentField;
        }
        set {
            this.recurrentPaymentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string successURL {
        get {
            return this.successURLField;
        }
        set {
            this.successURLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<long> targetGoId {
        get {
            return this.targetGoIdField;
        }
        set {
            this.targetGoIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<long> totalPrice {
        get {
            return this.totalPriceField;
        }
        set {
            this.totalPriceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:AxisEPaymentProvider")]
public partial class ECustomerData {
    
    private string cityField;
    
    private string countryCodeField;
    
    private string emailField;
    
    private string firstNameField;
    
    private string lastNameField;
    
    private string phoneNumberField;
    
    private string postalCodeField;
    
    private string streetField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string countryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string firstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string lastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string phoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string postalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:AxisEPaymentProvider")]
public partial class EPaymentMethod {
    
    private string codeField;
    
    private string descriptionField;
    
    private string logoField;
    
    private bool offlineField;
    
    private string paymentMethodField;
    
    private bool supportPreauthorizationField;
    
    private bool supportRecurrentField;
    
    private string supportedCurrencyField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string logo {
        get {
            return this.logoField;
        }
        set {
            this.logoField = value;
        }
    }
    
    /// <remarks/>
    public bool offline {
        get {
            return this.offlineField;
        }
        set {
            this.offlineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string paymentMethod {
        get {
            return this.paymentMethodField;
        }
        set {
            this.paymentMethodField = value;
        }
    }
    
    /// <remarks/>
    public bool supportPreauthorization {
        get {
            return this.supportPreauthorizationField;
        }
        set {
            this.supportPreauthorizationField = value;
        }
    }
    
    /// <remarks/>
    public bool supportRecurrent {
        get {
            return this.supportRecurrentField;
        }
        set {
            this.supportRecurrentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string supportedCurrency {
        get {
            return this.supportedCurrencyField;
        }
        set {
            this.supportedCurrencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:AxisEPaymentProvider")]
public partial class EBuyerCreateResult {
    
    private string buyerEmailField;
    
    private System.Nullable<long> buyerGoIdField;
    
    private string encryptedSignatureField;
    
    private System.Nullable<long> eshopGoIdField;
    
    private string resultField;
    
    private string resultDescriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string buyerEmail {
        get {
            return this.buyerEmailField;
        }
        set {
            this.buyerEmailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<long> buyerGoId {
        get {
            return this.buyerGoIdField;
        }
        set {
            this.buyerGoIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string encryptedSignature {
        get {
            return this.encryptedSignatureField;
        }
        set {
            this.encryptedSignatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<long> eshopGoId {
        get {
            return this.eshopGoIdField;
        }
        set {
            this.eshopGoIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string resultDescription {
        get {
            return this.resultDescriptionField;
        }
        set {
            this.resultDescriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:AxisEPaymentProvider")]
public partial class EBuyerCreate {
    
    private string buyerEmailField;
    
    private string encryptedSignatureField;
    
    private System.Nullable<long> eshopGoIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string buyerEmail {
        get {
            return this.buyerEmailField;
        }
        set {
            this.buyerEmailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string encryptedSignature {
        get {
            return this.encryptedSignatureField;
        }
        set {
            this.encryptedSignatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<long> eshopGoId {
        get {
            return this.eshopGoIdField;
        }
        set {
            this.eshopGoIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gate.gopay.cz/ws")]
public partial class ERecurrenceRequest {
    
    private string encryptedSignatureField;
    
    private string orderNumberField;
    
    private System.Nullable<long> parentPaymentSessionIdField;
    
    private System.Nullable<long> targetGoIdField;
    
    private System.Nullable<long> totalPriceField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string encryptedSignature {
        get {
            return this.encryptedSignatureField;
        }
        set {
            this.encryptedSignatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string orderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<long> parentPaymentSessionId {
        get {
            return this.parentPaymentSessionIdField;
        }
        set {
            this.parentPaymentSessionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<long> targetGoId {
        get {
            return this.targetGoIdField;
        }
        set {
            this.targetGoIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<long> totalPrice {
        get {
            return this.totalPriceField;
        }
        set {
            this.totalPriceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://gate.gopay.cz/ws")]
public partial class EPaymentResult {
    
    private string encryptedSignatureField;
    
    private System.Nullable<long> paymentSessionIdField;
    
    private string resultField;
    
    private string resultDescriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string encryptedSignature {
        get {
            return this.encryptedSignatureField;
        }
        set {
            this.encryptedSignatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<long> paymentSessionId {
        get {
            return this.paymentSessionIdField;
        }
        set {
            this.paymentSessionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string resultDescription {
        get {
            return this.resultDescriptionField;
        }
        set {
            this.resultDescriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:AxisEPaymentProvider")]
public partial class EPaymentSessionInfo {
    
    private string encryptedSignatureField;
    
    private System.Nullable<long> paymentSessionIdField;
    
    private System.Nullable<long> targetGoIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string encryptedSignature {
        get {
            return this.encryptedSignatureField;
        }
        set {
            this.encryptedSignatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<long> paymentSessionId {
        get {
            return this.paymentSessionIdField;
        }
        set {
            this.paymentSessionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<long> targetGoId {
        get {
            return this.targetGoIdField;
        }
        set {
            this.targetGoIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:AxisEPaymentProvider")]
public partial class EPaymentStatus {
    
    private string currencyField;
    
    private string encryptedSignatureField;
    
    private string orderNumberField;
    
    private string p1Field;
    
    private string p2Field;
    
    private string p3Field;
    
    private string p4Field;
    
    private System.Nullable<long> parentPaymentSessionIdField;
    
    private string paymentChannelField;
    
    private System.Nullable<long> paymentSessionIdField;
    
    private System.Nullable<bool> preAuthorizationField;
    
    private string productNameField;
    
    private System.Nullable<bool> recurrentPaymentField;
    
    private string resultField;
    
    private string resultDescriptionField;
    
    private string sessionStateField;
    
    private string sessionSubStateField;
    
    private string sessionSubStateDescField;
    
    private System.Nullable<long> targetGoIdField;
    
    private System.Nullable<long> totalPriceField;
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string encryptedSignature {
        get {
            return this.encryptedSignatureField;
        }
        set {
            this.encryptedSignatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string orderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string p1 {
        get {
            return this.p1Field;
        }
        set {
            this.p1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string p2 {
        get {
            return this.p2Field;
        }
        set {
            this.p2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string p3 {
        get {
            return this.p3Field;
        }
        set {
            this.p3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string p4 {
        get {
            return this.p4Field;
        }
        set {
            this.p4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<long> parentPaymentSessionId {
        get {
            return this.parentPaymentSessionIdField;
        }
        set {
            this.parentPaymentSessionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string paymentChannel {
        get {
            return this.paymentChannelField;
        }
        set {
            this.paymentChannelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<long> paymentSessionId {
        get {
            return this.paymentSessionIdField;
        }
        set {
            this.paymentSessionIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> preAuthorization {
        get {
            return this.preAuthorizationField;
        }
        set {
            this.preAuthorizationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string productName {
        get {
            return this.productNameField;
        }
        set {
            this.productNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<bool> recurrentPayment {
        get {
            return this.recurrentPaymentField;
        }
        set {
            this.recurrentPaymentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string resultDescription {
        get {
            return this.resultDescriptionField;
        }
        set {
            this.resultDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string sessionState {
        get {
            return this.sessionStateField;
        }
        set {
            this.sessionStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string sessionSubState {
        get {
            return this.sessionSubStateField;
        }
        set {
            this.sessionSubStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public string sessionSubStateDesc {
        get {
            return this.sessionSubStateDescField;
        }
        set {
            this.sessionSubStateDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<long> targetGoId {
        get {
            return this.targetGoIdField;
        }
        set {
            this.targetGoIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
    public System.Nullable<long> totalPrice {
        get {
            return this.totalPriceField;
        }
        set {
            this.totalPriceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void createPaymentCompletedEventHandler(object sender, createPaymentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class createPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal createPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EPaymentStatus Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EPaymentStatus)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void capturePaymentCompletedEventHandler(object sender, capturePaymentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class capturePaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal capturePaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EPaymentResult Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EPaymentResult)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void voidAuthorizationCompletedEventHandler(object sender, voidAuthorizationCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class voidAuthorizationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal voidAuthorizationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EPaymentResult Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EPaymentResult)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void createRecurrentPaymentCompletedEventHandler(object sender, createRecurrentPaymentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class createRecurrentPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal createRecurrentPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EPaymentStatus Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EPaymentStatus)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void refundPaymentCompletedEventHandler(object sender, refundPaymentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class refundPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal refundPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EPaymentResult Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EPaymentResult)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void paymentStatusCompletedEventHandler(object sender, paymentStatusCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class paymentStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal paymentStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EPaymentStatus Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EPaymentStatus)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void voidRecurrentPaymentCompletedEventHandler(object sender, voidRecurrentPaymentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class voidRecurrentPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal voidRecurrentPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EPaymentResult Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EPaymentResult)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void createBuyerCompletedEventHandler(object sender, createBuyerCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class createBuyerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal createBuyerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EBuyerCreateResult Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EBuyerCreateResult)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void touchCompletedEventHandler(object sender, touchCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class touchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal touchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void paymentMethodListCompletedEventHandler(object sender, paymentMethodListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class paymentMethodListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal paymentMethodListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public EPaymentMethod[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((EPaymentMethod[])(this.results[0]));
        }
    }
}
